/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class CustomerOrders extends javax.swing.JFrame {
String Vehicle_num , Order_Date, OrdersType;
int OrderID ;
DefaultTableModel model;
    /**
     * Creates new form CustomerOrders
     */
    public CustomerOrders() {
        initComponents();
        setRecordstoEmployees();
    }
public void setRecordstoEmployees(){
    try{
     Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carecaredb","root",""); 
     Statement st = con.createStatement();
     ResultSet rs = st.executeQuery("SELECT * FROM orders ");
     
     while(rs.next()){
     String OrdreId = rs.getString("orderId");
     String VehicleNum = rs.getString("Vehicle_Number");
     String OrderDates = rs.getString("OrderDate");
     String OrdrsType = rs.getString("OrderType");
     
     Object[] obj = {OrdreId,VehicleNum,OrderDates,OrdrsType} ;
     model = (DefaultTableModel) Order_tbl.getModel();
     model.addRow(obj);    
     }   
    }
    
    catch(Exception e){
        e.printStackTrace();
    }
    }

public boolean addOrder(){
    boolean isAdded = false;
    Vehicle_num = txt_vehicleNum.getText();
    Order_Date = txt_orderDate.getText();
    OrdersType = (String) OrderTypeCombo.getSelectedItem();
    try{
    Connection con = DbConnection.getConnection();
    String query = "INSERT INTO orders( Vehicle_Number, OrderDate, OrderType) VALUES (?,?,?)";
    PreparedStatement pst = con.prepareStatement(query);
    
    pst.setString(1, Vehicle_num);
    pst.setString(2, Order_Date);
    pst.setString(3, OrdersType);
    
    int rowCount = pst.executeUpdate();
    
    if(rowCount>0){
        isAdded = true;
    }
    else{
    isAdded = false;
    }
    }
    
    catch(Exception e){
    e.printStackTrace();
    }
    return isAdded;
}
public void clearTable(){
    DefaultTableModel model = (DefaultTableModel) Order_tbl.getModel();
    model.setRowCount(0);
}
public boolean UpdateBook(){
    boolean isUpdated = false;
    Vehicle_num = txt_vehicleNum.getText();
    Order_Date = txt_orderDate.getText();  
    try{
    Connection con = DbConnection.getConnection();
    String query = "UPDATE orders SET Vehicle_Number=?,OrderDate=? WHERE Vehicle_Number='"+Vehicle_num+"'";
    PreparedStatement pst = con.prepareStatement(query);
    
    pst.setString(1, Vehicle_num);
    pst.setString(2, Order_Date);
    
    int rowCount = pst.executeUpdate();
    
    if(rowCount>0){
    isUpdated = true;
    }
    else{
    isUpdated = false;
    }
    }
catch(Exception e){
e.printStackTrace();
}
return isUpdated;
}
public boolean DeleteOrder(){
Boolean isDeleted= false;
Vehicle_num = txt_vehicleNum.getText();

try{
    Connection con = DbConnection.getConnection();
    String query = "DELETE FROM orders WHERE Vehicle_Number=?";
    PreparedStatement pst = con.prepareStatement(query);
    
    pst.setString(1, Vehicle_num);
     int rowCount = pst.executeUpdate();
      if(rowCount>0){
    isDeleted = true;
    }
    else{
    isDeleted = false;
    }
}
catch (Exception e){
e.printStackTrace();
}
    
    
    return isDeleted;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_vehicleNum = new javax.swing.JTextField();
        Add_Customer = new rojerusan.RSMaterialButtonRectangle();
        Add_Customer1 = new rojerusan.RSMaterialButtonRectangle();
        Add_Customer2 = new rojerusan.RSMaterialButtonRectangle();
        txt_orderDate = new javax.swing.JTextField();
        OrderTypeCombo = new javax.swing.JComboBox<>();
        txt_Emailtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Order_tbl = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vehicle Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Order Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txt_vehicleNum.setBackground(new java.awt.Color(153, 153, 153));
        txt_vehicleNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vehicleNumActionPerformed(evt);
            }
        });
        jPanel1.add(txt_vehicleNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 310, 30));

        Add_Customer.setBackground(new java.awt.Color(255, 51, 51));
        Add_Customer.setText("delete");
        Add_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_CustomerActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 170, 50));

        Add_Customer1.setBackground(new java.awt.Color(0, 204, 51));
        Add_Customer1.setText("Create");
        Add_Customer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_Customer1MouseClicked(evt);
            }
        });
        Add_Customer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Customer1ActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Customer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 170, 50));

        Add_Customer2.setBackground(new java.awt.Color(0, 0, 0));
        Add_Customer2.setText("Update");
        Add_Customer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Customer2ActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Customer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 170, 50));

        txt_orderDate.setBackground(new java.awt.Color(153, 153, 153));
        txt_orderDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_orderDateActionPerformed(evt);
            }
        });
        jPanel1.add(txt_orderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 310, 30));

        OrderTypeCombo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        OrderTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Repair", "Repaint", "Spare Parts" }));
        jPanel1.add(OrderTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 310, 30));

        txt_Emailtxt.setBackground(new java.awt.Color(153, 153, 153));
        txt_Emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailtxtActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 310, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E mail");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, 530));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Return Home");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order Management");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Order_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Vehicle Number", "Email", "Order Date", "Order Type"
            }
        ));
        Order_tbl.setColorBackgoundHead(new java.awt.Color(0, 0, 0));
        Order_tbl.setRowHeight(30);
        Order_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Order_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Order_tbl);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 600, 530));

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_vehicleNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vehicleNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vehicleNumActionPerformed

    private void txt_orderDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_orderDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_orderDateActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
         HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void Order_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Order_tblMouseClicked
        int rowNo = Order_tbl.getSelectedRow();
        TableModel model = Order_tbl.getModel();
        
        txt_vehicleNum.setText(model.getValueAt(rowNo, 1).toString());
        txt_orderDate.setText(model.getValueAt(rowNo, 2).toString());
    }//GEN-LAST:event_Order_tblMouseClicked

    private void Add_Customer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Customer1MouseClicked

    }//GEN-LAST:event_Add_Customer1MouseClicked

    private void Add_Customer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Customer1ActionPerformed
              if(addOrder()==true){
              JOptionPane.showMessageDialog(this, "Order Added Succesfully ! ");
              clearTable();
              setRecordstoEmployees();
              }
              else {
              JOptionPane.showMessageDialog(this, "Order Addition Faliour ! ");
              }
    }//GEN-LAST:event_Add_Customer1ActionPerformed

    private void Add_Customer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Customer2ActionPerformed
        if(UpdateBook()==true){
              JOptionPane.showMessageDialog(this, "Order Updated Succesfully ! ");
              clearTable();
              setRecordstoEmployees();
              }
              else {
              JOptionPane.showMessageDialog(this, "Order Updation Faliour ! ");
              }
    }//GEN-LAST:event_Add_Customer2ActionPerformed

    private void txt_EmailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailtxtActionPerformed

    private void Add_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_CustomerActionPerformed
    if (DeleteOrder()==true){
    JOptionPane.showMessageDialog(this, "Order Deleted Succesfully ! ");
              clearTable();
              setRecordstoEmployees();
              }
              else {
              JOptionPane.showMessageDialog(this, "Order Deletion Faliour ! ");
    }
    }//GEN-LAST:event_Add_CustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle Add_Customer;
    private rojerusan.RSMaterialButtonRectangle Add_Customer1;
    private rojerusan.RSMaterialButtonRectangle Add_Customer2;
    private javax.swing.JComboBox<String> OrderTypeCombo;
    private rojerusan.RSTableMetro Order_tbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Emailtxt;
    private javax.swing.JTextField txt_orderDate;
    private javax.swing.JTextField txt_vehicleNum;
    // End of variables declaration//GEN-END:variables
}
