/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class EmployeeManagement extends javax.swing.JFrame {
String First_name , Last_name , Sontact , City , HiredDate , Email , Catogary;
int EmployeeID ;
DefaultTableModel model;
    /**
     * Creates new form CustomerOrders
     */
    public EmployeeManagement() {
        initComponents();
        setRecordstoEmployees();
    }


    public void setRecordstoEmployees(){
    try{
     Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carecaredb","root",""); 
     Statement st = con.createStatement();
     ResultSet rs = st.executeQuery("SELECT * FROM employees ");
     
     while(rs.next()){
     String EmployeeiD = rs.getString("EmployeeId");
     String Firstname = rs.getString("First_name");
     String Lastname = rs.getString("Last_Name");
     String city = rs.getString("City");
     String EMail = rs.getString("Email");
     String HireDate = rs.getString("hiredDate");
     String Cnumber = rs.getString("ContactNumber");
     String Cat = rs.getString("EmpStatus");
     
     Object[] obj = {EmployeeiD,Firstname,Lastname, EMail ,city , HireDate , Cnumber, Cat} ;
     model = (DefaultTableModel) Employee_tbl.getModel();
     model.addRow(obj);    
     }   
    }
    
    catch(Exception e){
        e.printStackTrace();
    }
    }
    
    public void clearTable(){
    DefaultTableModel model = (DefaultTableModel) Employee_tbl.getModel();
    model.setRowCount(0);
}
    public boolean addEmployee(){
    boolean isAdded = false;
    First_name = txt_firstname.getText();
    Last_name = txt_lastname.getText();
    City = txt_city.getText();
    HiredDate = txt_hiredDate.getText();
    Email = txt_Email.getText();
    Sontact = txt_contactNum.getText();
    Catogary = (String) Categorycombo.getSelectedItem();
    try{
    Connection con = DbConnection.getConnection();
    String query = "INSERT INTO employees( First_name, Last_name, City ,HiredDate, Email,ContactNumber , Category ) VALUES (?,?,?,?,?,?,?)";
    PreparedStatement pst = con.prepareStatement(query);
    
    pst.setString(1, First_name);
    pst.setString(2, Last_name);
    pst.setString(3, City);
    pst.setString(4, HiredDate);
    pst.setString(5, Email);
    pst.setString(6, Sontact);
    pst.setString(7, Catogary);
    
    int rowCount = pst.executeUpdate();
    
    if(rowCount>0){
        isAdded = true;
    }
    else{
    isAdded = false;
    }
    }
    
    catch(Exception e){
    e.printStackTrace();
    }
    return isAdded;
    }
    
    public boolean UplateEmployee(){   
    boolean isUpdated = false;
    First_name = txt_firstname.getText();
    Last_name = txt_lastname.getText();
    City = txt_city.getText();
    HiredDate = txt_hiredDate.getText();
    Email = txt_Email.getText();
    Sontact = txt_contactNum.getText();
    Catogary = (String) Categorycombo.getSelectedItem();
    try{
    Connection con = DbConnection.getConnection();
    String query = "UPDATE employees SET First_name=?,Last_name=? , City=?,HiredDate=?, Email=?, ContactNumber=?, Category=? WHERE Email='"+Email+"'";
    PreparedStatement pst = con.prepareStatement(query);
    
    pst.setString(1, First_name);
    pst.setString(2, Last_name);
    pst.setString(3, City);
    pst.setString(4, HiredDate);
    pst.setString(5, Email);
    pst.setString(6, Sontact);
    pst.setString(7, Catogary);
    
    int rowCount = pst.executeUpdate();
    
    if(rowCount>0){
    isUpdated = true;
    }
    else{
    isUpdated = false;
    }
    }
catch(Exception e){
e.printStackTrace();
}
return isUpdated;
    }
    
    public boolean DeleteEmployee(){
Boolean isDeleted= false;
  Email = txt_Email.getText();

try{
    Connection con = DbConnection.getConnection();
    String query = "DELETE FROM employees WHERE Email=?";
    PreparedStatement pst = con.prepareStatement(query);
    
    pst.setString(1, Email);
     int rowCount = pst.executeUpdate();
      if(rowCount>0){
    isDeleted = true;
    }
    else{
    isDeleted = false;
    }
}
catch (Exception e){
e.printStackTrace();
}
return isDeleted;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_contactNum = new javax.swing.JTextField();
        Add_Customer = new rojerusan.RSMaterialButtonRectangle();
        Add_Customer1 = new rojerusan.RSMaterialButtonRectangle();
        Add_Customer2 = new rojerusan.RSMaterialButtonRectangle();
        jLabel8 = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_hiredDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Categorycombo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Employee_tbl = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        txt_firstname.setBackground(new java.awt.Color(153, 153, 153));
        txt_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, -1));

        txt_lastname.setBackground(new java.awt.Color(153, 153, 153));
        txt_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E mail");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 130, -1));

        txt_Email.setBackground(new java.awt.Color(153, 153, 153));
        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 170, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact Number");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 120, -1));

        txt_contactNum.setBackground(new java.awt.Color(153, 153, 153));
        txt_contactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactNumActionPerformed(evt);
            }
        });
        jPanel1.add(txt_contactNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 170, 30));

        Add_Customer.setBackground(new java.awt.Color(255, 51, 51));
        Add_Customer.setText("delete");
        Add_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_CustomerActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 170, 50));

        Add_Customer1.setBackground(new java.awt.Color(0, 204, 51));
        Add_Customer1.setText("Create");
        Add_Customer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Customer1ActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Customer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 170, 50));

        Add_Customer2.setBackground(new java.awt.Color(0, 0, 0));
        Add_Customer2.setText("Update");
        Add_Customer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Customer2ActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Customer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 170, 50));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("City");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 70, -1));

        txt_city.setBackground(new java.awt.Color(153, 153, 153));
        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });
        jPanel1.add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 170, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hired Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 80, -1));

        txt_hiredDate.setBackground(new java.awt.Color(153, 153, 153));
        txt_hiredDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hiredDateActionPerformed(evt);
            }
        });
        jPanel1.add(txt_hiredDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 170, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Catogary");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 70, -1));

        Categorycombo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Categorycombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spare Parts", "Paint", "Repair" }));
        jPanel1.add(Categorycombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 190));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Return Home");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee Management");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        Employee_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Email", "Contact", "Address", "Hired Date", "Position", "Catogary"
            }
        ));
        Employee_tbl.setColorBackgoundHead(new java.awt.Color(0, 0, 0));
        Employee_tbl.setRowHeight(30);
        Employee_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Employee_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Employee_tbl);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1000, 340));

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstnameActionPerformed

    private void txt_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastnameActionPerformed

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_contactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactNumActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void txt_hiredDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hiredDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hiredDateActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void Add_Customer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Customer1ActionPerformed
        if(addEmployee()==true){
        JOptionPane.showMessageDialog(this, "Employee Added Succesfully");
        clearTable();
        setRecordstoEmployees();
        }
        else {
        JOptionPane.showMessageDialog(this, "Employee Adding Faliur");
        }
    }//GEN-LAST:event_Add_Customer1ActionPerformed

    private void Add_Customer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Customer2ActionPerformed
        if(UplateEmployee()==true){
        JOptionPane.showMessageDialog(this, "Employee Updated Succesfully");
        clearTable();
        setRecordstoEmployees();
        }
         else {
        JOptionPane.showMessageDialog(this, "Employee Updation Faliur");
        }
    }//GEN-LAST:event_Add_Customer2ActionPerformed

    private void Add_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_CustomerActionPerformed
        if (DeleteEmployee()==true){
    JOptionPane.showMessageDialog(this, "Order Deleted Succesfully ! ");
              clearTable();
              setRecordstoEmployees();
              }
              else {
              JOptionPane.showMessageDialog(this, "Order Deletion Faliour ! ");
    }  
    }//GEN-LAST:event_Add_CustomerActionPerformed

    private void Employee_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee_tblMouseClicked
                int rowNo = Employee_tbl.getSelectedRow();
                TableModel model = Employee_tbl.getModel();
        txt_firstname.setText(model.getValueAt(rowNo, 1).toString());
        txt_lastname.setText(model.getValueAt(rowNo, 2).toString());
        txt_city.setText(model.getValueAt(rowNo, 3).toString());
        txt_hiredDate.setText(model.getValueAt(rowNo, 5).toString());
        txt_Email.setText(model.getValueAt(rowNo, 4).toString());
        txt_contactNum.setText(model.getValueAt(rowNo, 6).toString());
    }//GEN-LAST:event_Employee_tblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle Add_Customer;
    private rojerusan.RSMaterialButtonRectangle Add_Customer1;
    private rojerusan.RSMaterialButtonRectangle Add_Customer2;
    private javax.swing.JComboBox<String> Categorycombo;
    private rojerusan.RSTableMetro Employee_tbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_contactNum;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_hiredDate;
    private javax.swing.JTextField txt_lastname;
    // End of variables declaration//GEN-END:variables
}
