/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;


import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class HomePage extends javax.swing.JFrame {
String Process , Vehicle_num , EmpStatus;
int OrderID , EmployeeID;
DefaultTableModel model;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
       checkDate();
       setRecordstoAvailableOrders();
       setRecordstoAvailableEmployees();
    }
    
    public void checkDate(){
    
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("YYY/MM/DD  HH:MM");
        LocalDateTime  now= LocalDateTime.now();
        Date_txt.setText(dtf.format(now));
    }
    
    public void setRecordstoAvailableOrders(){
    try{
     Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carecaredb","root",""); 
     Statement st = con.createStatement();
     ResultSet rs = st.executeQuery("SELECT * FROM orders WHERE Status = 'New' ");
     
     while(rs.next()){
     String OrderId = rs.getString("orderId");
     String vehicleNum = rs.getString("Vehicle_Number");
     String Status = rs.getString("Status");
     
     Object[] obj = {OrderId,vehicleNum,Status} ;
     model = (DefaultTableModel) AvailableOrders_tbl.getModel();
     model.addRow(obj);    
     }   
    }
    
    catch(Exception e){
        e.printStackTrace();
    }
    }
    public void setRecordstoAvailableEmployees(){
    try{
     Connection con = DbConnection.getConnection();
     Statement st = con.createStatement();
     ResultSet rs = st.executeQuery("SELECT * FROM employees WHERE EmpStatus = 'Free' ");
     
     while(rs.next()){
     String EmpId = rs.getString("EmployeeId");
     String EmpStatus = rs.getString("EmpStatus");
     
     Object[] obj = {EmpId,EmpStatus} ;
     model = (DefaultTableModel) AvailableEmp_tbl.getModel();
     model.addRow(obj);    
     }   
    }
    
    catch(Exception e){
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_LogEmail = new javax.swing.JTextField();
        Date_txt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        SearchByState_txt = new javax.swing.JTextField();
        searchByVehicleNum = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        searchByVehicleNum1 = new rojerusan.RSMaterialButtonRectangle();
        searchByVehicleNum2 = new rojerusan.RSMaterialButtonRectangle();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        OrderId_txt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        itemId_txt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill_txt = new javax.swing.JTextArea();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        Quantity_txt = new javax.swing.JTextField();
        AddbillBtn = new rojerusan.RSMaterialButtonRectangle();
        Discount_txt1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        AddbillBtn1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AvailableEmp_tbl = new rojerusan.RSTableMetro();
        jScrollPane3 = new javax.swing.JScrollPane();
        AvailableOrders_tbl = new rojerusan.RSTableMetro();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Date :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, -1));

        txt_LogEmail.setBackground(new java.awt.Color(153, 153, 153));
        txt_LogEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_LogEmailFocusLost(evt);
            }
        });
        jPanel1.add(txt_LogEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 310, 40));

        Date_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(Date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 180, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1280, 75));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Road Rage", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Care Care");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Wellcome ,");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel7.setText("home");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, 70));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("customers");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 300, 70));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("notifications");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 300, 70));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("employees");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 70));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("suppliers");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 300, 70));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("A25-SQUANOVA", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("admin");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 240, 30));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("inventory");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 300, 70));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("reports");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 300, 70));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("job allocation");
        jPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 300, 70));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(240, 240, 240));
        rSMaterialButtonRectangle1.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle1.setText("Log Out");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 860, 200, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 1160));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("No. Of Users");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("No. Of Vehicles");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 110, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("No. Of Suppliers");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 130, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3.setText("10");
        jTextField3.setBorder(null);
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 70, 60, 40));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField6.setText("10");
        jTextField6.setBorder(null);
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 60, 40));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField7.setText("10");
        jTextField7.setBorder(null);
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 60, 40));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField8.setText("10");
        jTextField8.setBorder(null);
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 30, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Search for Stage :");

        SearchByState_txt.setBackground(new java.awt.Color(153, 153, 153));
        SearchByState_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchByState_txtFocusLost(evt);
            }
        });
        SearchByState_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByState_txtActionPerformed(evt);
            }
        });

        searchByVehicleNum.setBackground(new java.awt.Color(204, 204, 204));
        searchByVehicleNum.setForeground(new java.awt.Color(0, 0, 0));
        searchByVehicleNum.setText("SEARCH");
        searchByVehicleNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchByVehicleNumMouseClicked(evt);
            }
        });
        searchByVehicleNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByVehicleNumActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        searchByVehicleNum1.setBackground(new java.awt.Color(255, 255, 255));
        searchByVehicleNum1.setForeground(new java.awt.Color(0, 0, 0));
        searchByVehicleNum1.setText("Sent notification to customer");
        searchByVehicleNum1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchByVehicleNum1MouseClicked(evt);
            }
        });
        searchByVehicleNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByVehicleNum1ActionPerformed(evt);
            }
        });

        searchByVehicleNum2.setBackground(new java.awt.Color(0, 0, 0));
        searchByVehicleNum2.setText("Monthly report generate");
        searchByVehicleNum2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchByVehicleNum2MouseClicked(evt);
            }
        });
        searchByVehicleNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByVehicleNum2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(SearchByState_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(searchByVehicleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(searchByVehicleNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchByVehicleNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchByState_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchByVehicleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchByVehicleNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByVehicleNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 530, 240));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Order Id");
        jPanel13.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        OrderId_txt.setBackground(new java.awt.Color(153, 153, 153));
        OrderId_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                OrderId_txtFocusLost(evt);
            }
        });
        jPanel13.add(OrderId_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 210, 40));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Item Id");
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        itemId_txt.setBackground(new java.awt.Color(153, 153, 153));
        itemId_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemId_txtFocusLost(evt);
            }
        });
        jPanel13.add(itemId_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 210, 40));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Quantity");
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        bill_txt.setColumns(20);
        bill_txt.setRows(5);
        jScrollPane1.setViewportView(bill_txt);

        jPanel13.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 290, 590));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle2.setText("Print");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel13.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 230, 60));

        Quantity_txt.setBackground(new java.awt.Color(153, 153, 153));
        Quantity_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Quantity_txtFocusLost(evt);
            }
        });
        jPanel13.add(Quantity_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 210, 40));

        AddbillBtn.setBackground(new java.awt.Color(255, 255, 255));
        AddbillBtn.setForeground(new java.awt.Color(0, 0, 0));
        AddbillBtn.setText("Add");
        AddbillBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddbillBtnMouseClicked(evt);
            }
        });
        AddbillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbillBtnActionPerformed(evt);
            }
        });
        jPanel13.add(AddbillBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 160, 60));

        Discount_txt1.setBackground(new java.awt.Color(153, 153, 153));
        Discount_txt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Discount_txt1FocusLost(evt);
            }
        });
        jPanel13.add(Discount_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 210, 40));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Discount");
        jPanel13.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        AddbillBtn1.setBackground(new java.awt.Color(255, 255, 255));
        AddbillBtn1.setForeground(new java.awt.Color(0, 0, 0));
        AddbillBtn1.setText("Enter");
        AddbillBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddbillBtn1MouseClicked(evt);
            }
        });
        AddbillBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbillBtn1ActionPerformed(evt);
            }
        });
        jPanel13.add(AddbillBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 160, 60));

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 640, 640));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        jLabel8.setText("check out");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        AvailableEmp_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee_Id", "Status"
            }
        ));
        AvailableEmp_tbl.setColorBackgoundHead(new java.awt.Color(153, 153, 153));
        AvailableEmp_tbl.setRowHeight(30);
        jScrollPane2.setViewportView(AvailableEmp_tbl);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 530, 190));

        AvailableOrders_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order_Id", "Vehicle_Num", "Process"
            }
        ));
        AvailableOrders_tbl.setColorBackgoundHead(new java.awt.Color(153, 153, 153));
        AvailableOrders_tbl.setRowHeight(30);
        jScrollPane3.setViewportView(AvailableOrders_tbl);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 530, 190));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("No. Of Employees");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 130, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Orders");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 130, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Employees");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 130, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 1280, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void txt_LogEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_LogEmailFocusLost

    }//GEN-LAST:event_txt_LogEmailFocusLost

    private void OrderId_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OrderId_txtFocusLost

    }//GEN-LAST:event_OrderId_txtFocusLost

    private void itemId_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemId_txtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_itemId_txtFocusLost

    private void SearchByState_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchByState_txtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchByState_txtFocusLost

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void searchByVehicleNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByVehicleNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByVehicleNumActionPerformed

    private void Quantity_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Quantity_txtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Quantity_txtFocusLost

    private void AddbillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbillBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddbillBtnActionPerformed

    private void AddbillBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbillBtnMouseClicked
                                  
    String orderId = OrderId_txt.getText();

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carecaredb", "root", ""); 

        String query = "SELECT CustomerID, OrderDate, OrderType FROM orders WHERE CustomerID = ?";

        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, orderId);

        ResultSet rs = pst.executeQuery();

        billHeader();

        if (rs.next()) {
            String orderType = rs.getString("OrderType");

            bill_txt.append("OrderType: " + orderType);

            if(orderType.contentEquals("SpareParts")){
            
            }
            
        } else {
            bill_txt.append("\n\nNo order found for CustomerID: " + orderId);
        }
       
        rs.close();
        pst.close();
        con.close();
        billFooter();
    } catch(Exception e){
        e.printStackTrace();
    }  
}
    
    public void searchByVehicleNum(){
    
    }

public void billHeader() {
    bill_txt.append("======================================"
            + "\n"
            + "\n"
            + "\t" + "   CARE CARE"
            + "\n"
            + "             Vehicle Repairing and Maintenance"
            + "\n"
            + "                       13/68 , Kurunegala"
            + "\n"
            + "\n"
            + "======================================");
    }//GEN-LAST:event_AddbillBtnMouseClicked
    public void billFooter() {
    bill_txt.append("\n"
            + "            A Clean Vehicle tells more About You "
            + "\n"
            + "                          CARE CARE"
            + "\n"
            + "                   Vehicle service and repair "
            +"\n"
            + "                       13/68 , Kurunegala"
            + "\n"
            + "\n"
            + "======================================");
    }
    private void Discount_txt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Discount_txt1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Discount_txt1FocusLost

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked

    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        EmployeeManagement Employee = new EmployeeManagement();
        Employee.setVisible(true);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        SupplierManagement Supplier = new SupplierManagement();
        Supplier.setVisible(true);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        InventoryManagement Inventory = new InventoryManagement();
        Inventory.setVisible(true);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        Notification Notifications = new Notification();
        Notifications.setVisible(true);
    }//GEN-LAST:event_jPanel11MouseClicked

    private void SearchByState_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByState_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchByState_txtActionPerformed

    private void searchByVehicleNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByVehicleNumMouseClicked
        
    }//GEN-LAST:event_searchByVehicleNumMouseClicked

    private void AddbillBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbillBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddbillBtn1MouseClicked

    private void AddbillBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbillBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddbillBtn1ActionPerformed

    private void searchByVehicleNum1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByVehicleNum1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByVehicleNum1MouseClicked

    private void searchByVehicleNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByVehicleNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByVehicleNum1ActionPerformed

    private void searchByVehicleNum2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByVehicleNum2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByVehicleNum2MouseClicked

    private void searchByVehicleNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByVehicleNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByVehicleNum2ActionPerformed

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
     
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
      
    }//GEN-LAST:event_jLabel17MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle AddbillBtn;
    private rojerusan.RSMaterialButtonRectangle AddbillBtn1;
    private rojerusan.RSTableMetro AvailableEmp_tbl;
    private rojerusan.RSTableMetro AvailableOrders_tbl;
    private javax.swing.JLabel Date_txt;
    private javax.swing.JTextField Discount_txt1;
    private javax.swing.JTextField OrderId_txt;
    private javax.swing.JTextField Quantity_txt;
    private javax.swing.JTextField SearchByState_txt;
    private javax.swing.JTextArea bill_txt;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField itemId_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle searchByVehicleNum;
    private rojerusan.RSMaterialButtonRectangle searchByVehicleNum1;
    private rojerusan.RSMaterialButtonRectangle searchByVehicleNum2;
    private javax.swing.JTextField txt_LogEmail;
    // End of variables declaration//GEN-END:variables

}