/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.mail.Session;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
/**
 *
 * @author User
 */
public class Notification extends javax.swing.JFrame {

    /**
     * Creates new form Notification
     */
    public Notification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        txt_EmpEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_fromMail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_EmpMessage = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_empSubject = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        jLabel8 = new javax.swing.JLabel();
        txt_custEmail = new javax.swing.JTextField();
        txt_fromEmail = new javax.swing.JLabel();
        txt_custSubj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_custmessage = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_frmEmil1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle1.setText("send Email to Employee");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel4.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 260, 60));

        txt_EmpEmail.setBackground(new java.awt.Color(153, 153, 153));
        txt_EmpEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmpEmailActionPerformed(evt);
            }
        });
        jPanel4.add(txt_EmpEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Subject");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, 50));

        txt_fromMail.setBackground(new java.awt.Color(153, 153, 153));
        txt_fromMail.setText("carecare.vehicleservice@gmail.com");
        txt_fromMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fromMailActionPerformed(evt);
            }
        });
        jPanel4.add(txt_fromMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Employee Email");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 40));

        txt_EmpMessage.setBackground(new java.awt.Color(153, 153, 153));
        txt_EmpMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmpMessageActionPerformed(evt);
            }
        });
        jPanel4.add(txt_EmpMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 240, 90));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("From Email");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, 40));

        txt_empSubject.setBackground(new java.awt.Color(153, 153, 153));
        txt_empSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empSubjectActionPerformed(evt);
            }
        });
        jPanel4.add(txt_empSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("From Email");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, 40));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Return Home");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Notifications");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle2.setText("send Email to customer");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 260, 60));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Customer Email");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 40));

        txt_custEmail.setBackground(new java.awt.Color(153, 153, 153));
        txt_custEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_custEmailActionPerformed(evt);
            }
        });
        jPanel3.add(txt_custEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 30));

        txt_fromEmail.setBackground(new java.awt.Color(255, 255, 255));
        txt_fromEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_fromEmail.setText("From Email");
        jPanel3.add(txt_fromEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, 40));

        txt_custSubj.setBackground(new java.awt.Color(153, 153, 153));
        txt_custSubj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_custSubjActionPerformed(evt);
            }
        });
        jPanel3.add(txt_custSubj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Message");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, 50));

        txt_custmessage.setBackground(new java.awt.Color(153, 153, 153));
        txt_custmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_custmessageActionPerformed(evt);
            }
        });
        jPanel3.add(txt_custmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 240, 90));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Subject");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, 50));

        txt_frmEmil1.setBackground(new java.awt.Color(153, 153, 153));
        txt_frmEmil1.setText("carecare.vehicleservice@gmail.com");
        txt_frmEmil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_frmEmil1ActionPerformed(evt);
            }
        });
        jPanel3.add(txt_frmEmil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(600, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        
        String ToEmail = txt_custEmail.getText(); 
        String FromEmail = txt_frmEmil1.getText(); 
        String FromEmailPassword ="Sliit@94";//You email Password
        String Subjects = txt_custSubj.getText(); 
        
        Properties properties = new Properties();
        properties.put("mail.smtp.auth","true");
        properties.put("mail.smtp.strattle.enable","true");
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.put("mail.smtp.port","587");
        
        Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator(){
        protected PasswordAuthentication getPasswordAuthentication(){
        return new PasswordAuthentication (FromEmail,FromEmailPassword);
        }
        });
        
        try{
            MimeMessage message = new  MimeMessage(session);
            message.setFrom(new InternetAddress(FromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(ToEmail));
            message.setSubject(Subjects);
            message.setText(txt_custmessage.getText());
            Transport.send(message);
        }
        catch(Exception e){
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        
        String ToEmail = txt_EmpEmail.getText(); 
        String FromEmail = txt_fromMail.getText(); 
        String FromEmailPassword ="Sliit@94";//You email Password
        String Subjects = txt_empSubject.getText(); 
        
        Properties properties = new Properties();
        properties.put("mail.smtp.auth","true");
        properties.put("mail.smtp.strattle.enable","true");
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.put("mail.smtp.port","587");
        
        Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator(){
        protected PasswordAuthentication getPasswordAuthentication(){
        return new PasswordAuthentication (FromEmail,FromEmailPassword);
        }
        });
        
        try{
            MimeMessage message = new  MimeMessage(session);
            message.setFrom(new InternetAddress(FromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(ToEmail));
            message.setSubject(Subjects);
            message.setText(txt_EmpMessage.getText());
            Transport.send(message);
        }
        catch(Exception e){
        e.printStackTrace();
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void txt_custEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_custEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_custEmailActionPerformed

    private void txt_custSubjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_custSubjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_custSubjActionPerformed

    private void txt_custmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_custmessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_custmessageActionPerformed

    private void txt_EmpEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmpEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmpEmailActionPerformed

    private void txt_fromMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fromMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fromMailActionPerformed

    private void txt_EmpMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmpMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmpMessageActionPerformed

    private void txt_frmEmil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_frmEmil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_frmEmil1ActionPerformed

    private void txt_empSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empSubjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private javax.swing.JTextField txt_EmpEmail;
    private javax.swing.JTextField txt_EmpMessage;
    private javax.swing.JTextField txt_custEmail;
    private javax.swing.JTextField txt_custSubj;
    private javax.swing.JTextField txt_custmessage;
    private javax.swing.JTextField txt_empSubject;
    private javax.swing.JTextField txt_frmEmil1;
    private javax.swing.JLabel txt_fromEmail;
    private javax.swing.JTextField txt_fromMail;
    // End of variables declaration//GEN-END:variables
}
